import { PostCardModel } from './ui/post_card/post-card.model';
import { TabModel } from './ui/tabs/tab';

export const tabsModels: TabModel[] = [
  { id: 1, name: 'All' },
  { id: 2, name: 'My favorites' },
  { id: 3, name: 'Popular', isDisabled: true },
];

export const postCardModels: PostCardModel[] = [
  {
    id: 1,
    image: 'https://i.pinimg.com/564x/2d/9f/67/2d9f676a7210c693186dac6c61a17ac9.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-27',
    lesson_num: 1,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 1,
  },
  {
    id: 2,
    image: 'https://i.pinimg.com/564x/90/d5/4e/90d54e958a209755a40e57e5a9e19e57.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 2,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 2,
  },
  {
    id: 3,
    image: 'https://i.pinimg.com/564x/6a/d2/d9/6ad2d91c6173a208bccd951587ab4d2d.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 3,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 3,
  },
  {
    id: 4,
    image: 'https://i.pinimg.com/564x/43/2b/85/432b8511c3f1c1dbcfdb74609b387c8c.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 4,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 4,
  },
  {
    id: 5,
    image: 'https://i.pinimg.com/564x/f3/fa/29/f3fa2998529605eeb6d67d429c68a13b.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 5,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 5,
  },
  {
    id: 6,
    image: 'https://i.pinimg.com/564x/18/f2/9f/18f29f9150439e164fbff117dad05a94.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 6,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 6,
  },
  {
    id: 7,
    image: 'https://i.pinimg.com/564x/a6/74/24/a674240f62300813e1bcdfdc01aac8a1.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 7,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 7,
  },
  {
    id: 8,
    image: 'https://i.pinimg.com/564x/6a/d2/d9/6ad2d91c6173a208bccd951587ab4d2d.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 8,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 8,
  },
  {
    id: 9,
    image: 'https://i.pinimg.com/564x/70/3c/b7/703cb7f48cab85cf06a235594b704dfd.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 9,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 9,
  },
  {
    id: 10,
    image: 'https://i.pinimg.com/564x/b5/51/d4/b551d434cb5097e41f673e1e93c1c492.jpg',
    text: 'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    date: '2023-08-28',
    lesson_num: 10,
    title: 'Astronauts prep for new solar arrays on nearly seven-hour spacewalk',
    author: 10,
  },

];
